/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import UserInterface.BebidaCadastrar;

/**
 *
 * @author Victor
 */
public class CervejariaForm extends javax.swing.JFrame {

    /**
     * Creates new form CervejariaForm
     */
    public CervejariaForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton6 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TelaPrincipal");
        setResizable(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cliente", "Vendedor", "Bebidas", "Comidas", "Nota Fiscal" }));

        jButton6.setText("Acessar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cadastrar", "Consultar", "Atualizar", "Deletar" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(211, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE))
                .addGap(339, 339, 339))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1169, 721));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int d = jComboBox1.getSelectedIndex();
        int e = jComboBox2.getSelectedIndex();
        if (d == 0 && e == 0) {
            ClienteCadastro clienteCombo0 = new ClienteCadastro();
            clienteCombo0.setVisible(true);
            clienteCombo0.setLocationRelativeTo(null);
        }
        if (d == 0 && e == 1) {
            ClienteConsulta clienteCombo1 = new ClienteConsulta();
            clienteCombo1.setVisible(true);
            clienteCombo1.setLocationRelativeTo(null);
        }
        if (d == 0 && e == 2) {
            ClienteAtualizar clienteCombo2 = new ClienteAtualizar();
            clienteCombo2.setVisible(true);
            clienteCombo2.setLocationRelativeTo(null);
        }
        if (d == 0 && e == 3) {
            ClienteDelete clienteCombo3 = new ClienteDelete();
            clienteCombo3.setVisible(true);
            clienteCombo3.setLocationRelativeTo(null);
        }

        if (d == 1 && e == 0) {
            VendedorCadastro vendedorCombo0 = new VendedorCadastro();
            vendedorCombo0.setVisible(true);
            vendedorCombo0.setLocationRelativeTo(null);
        }
        if (d == 1 && e == 1) {
            VendedorConsultar vendedorCombo1 = new VendedorConsultar();
            vendedorCombo1.setVisible(true);
            vendedorCombo1.setLocationRelativeTo(null);
        }
        if (d == 1 && e == 2) {
            VendedorAtualizar vendedorCombo2 = new VendedorAtualizar();
            vendedorCombo2.setVisible(true);
            vendedorCombo2.setLocationRelativeTo(null);
        }
        if (d == 1 && e == 3) {
            VendedorDeletar vendedorCombo3 = new VendedorDeletar();
            vendedorCombo3.setVisible(true);
            vendedorCombo3.setLocationRelativeTo(null);
        }
        if (d == 2 && e == 0) {
            BebidaCadastrar bebidaCombo0 = new BebidaCadastrar();
            bebidaCombo0.setVisible(true);
            bebidaCombo0.setLocationRelativeTo(null);
        }
        if (d == 2 && e == 1) {
            BebidaConsultar bebidaCombo1 = new BebidaConsultar();
            bebidaCombo1.setVisible(true);
            bebidaCombo1.setLocationRelativeTo(null);
        }
        if (d == 2 && e == 2) {
            BebidaAtualizar bebidaCombo2 = new BebidaAtualizar();
            bebidaCombo2.setVisible(true);
            bebidaCombo2.setLocationRelativeTo(null);
        }
        if (d == 2 && e == 3) {
            BebidaAtualizar bebidaCombo2 = new BebidaAtualizar();
            bebidaCombo2.setVisible(true);
            bebidaCombo2.setLocationRelativeTo(null);
        }
        if (d == 3 && e == 0) {
            ComidaCadastro comidaCombo0 = new ComidaCadastro();
            comidaCombo0.setVisible(true);
            comidaCombo0.setLocationRelativeTo(null);
        }
        if (d == 3 && e == 1) {
            ComidaConsultar comidaCombo1 = new ComidaConsultar();
            comidaCombo1.setVisible(true);
            comidaCombo1.setLocationRelativeTo(null);
        }
        if (d == 3 && e == 2) {
            ComidaAtualizar comidaCombo2 = new ComidaAtualizar();
            comidaCombo2.setVisible(true);
            comidaCombo2.setLocationRelativeTo(null);
        }
        if (d == 3 && e == 3) {
            ComidaDeletar comidaCombo3 = new ComidaDeletar();
            comidaCombo3.setVisible(true);
            comidaCombo3.setLocationRelativeTo(null);
        }
        if (d==4 && e == 0) {
            NotaFiscalCadastrar notaCombo0 = new NotaFiscalCadastrar();
            notaCombo0.setVisible(true);
            notaCombo0.setLocationRelativeTo(null);
        }
        if (d==4 && e == 1) {
            NotaFiscalConsultar notaCombo1 = new NotaFiscalConsultar();
            notaCombo1.setVisible(true);
            notaCombo1.setLocationRelativeTo(null);
        }
        if (d==4 && e == 2) {
            NotaFiscalAtualizar notaCombo2 = new NotaFiscalAtualizar();
            notaCombo2.setVisible(true);
            notaCombo2.setLocationRelativeTo(null);
        }
        if (d==4 && e == 3) {
            NotaFiscalDeletar notaCombo3 = new NotaFiscalDeletar();
            notaCombo3.setVisible(true);
            notaCombo3.setLocationRelativeTo(null);
        }
                
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed



   

  

    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CervejariaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CervejariaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CervejariaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CervejariaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CervejariaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
